[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "vAxSkkVFzGbDb2aRyAEC45pD793tYjj7rfGJwMvab3a"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dayanarp/.config/solana/dayana.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
